[X] Make it a flightsql server
This is the first iteration that triggers the bug. However, it uses an
external python flightsql client (based on
https://github.com/influxdata/flightsql-dbapi). At this point I will
start strippimg things back until I have a self-contained reproducer and
zero in on the root cause.

thread 'tokio-runtime-worker' panicked at src/main.rs:105:84:
called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: Other, error: JoinError { source: JoinError::Panic(Id(204), "A Tokio 1.x context was found, but timers are disabled. Call `enable_time` on the runtime builder to enable timers.", ...) } })